version: '2'
services:
  backup:
    image: fbieringer/odoo-backup
    restart: always
    volumes:

      # Output directory of your backups
      - ./backup:/backup

      # For a sql dump backup mount the filestore into the container
      # - odoo-web-data:/filestore

    environment:

      # Use Backup dir to redirect backup directory
      #- BACKUP_DIR=/backup

      # Name of the odoo database you want to backup
      - ODOO_DATABASE=odoo

      # Master password for the instance
      - ADMIN_PASSWORD=admin

      # URL where your odoo is available
      - URL=https://odoo.example.com

      # Schedule for your backups
      - SCHEDULE=*/30 * * * *

      # Use DB Parameters to start direct sql dump
      # - DB_HOST=db
      # - DB_USER=odoo
      # - DB_PASSWORD=odoo
      # - ODOO_DATABASE=odoo